### ISSUE TITLE
Possible to use this with Unity3d?

### ISSUE THREAD

**Issue by MostHated** [chrisa23/Fibrous#3]
Hey there,
    I know this is probably a long shot but I am using Unity3d 2018.1 which uses .net framework 4.6 and I was told that now since it uses a higher version of .net that I should be able to utilize more of the TPL. I have a game server framework that was originally made to work in a Windows console application that was setup using ThreadFiber, PoolFiber, a things of that nature but I am trying to make it work within Unity instead of within the Windows console application which requires (from what I userstand) things to be moved to the main thread when executed or something of that nature. 
  
Do you happen to have any experience or knowledge on how I might be able to use this system with Unity3d so I can convert what I currently have?

Thanks!

**Comment by chrisa23** [comment]
Hey,

I'm not familiar with Unity3d and its threading.  WPF and Win Forms require code to update the UI to be ran from the Dispatcher and UI thread respectively, which may be similar to Unity3d.  The DispatcherFiber and FormFiber might give you some ideas of how to force a fiber receiving an event to dispatch it on a particular thread.  You could possibly create a UnityFiber with that dispatch logic.  

I will try and look some to see if I can help you solve this.  Shouldn't be hard.

Thanks,
Chris

**Comment by MostHated** [comment]
Hey there,
    I definitely appreciate it. If it helps any, this is essentially what the code looks like that I am trying to use. It is not this project exactly but is the only example online I could find and most all of it is the same as what mine is using.

https://github.com/NickolayKabash/XO/blob/master/input/src/SpaceBattle/MultiplayerGameFramework.Networking/Concurrency/PoolFiber.cs

The code in the framework I am trying to use is broken up more with each class in its own file and such but the way its used is the same. I just am not sure and trying to figure out what parts of it would need to be changed to work with Unity. Someone told me that since Unity 2018.1 is using .net 4.6 the "TPL" should be compatible for a lot of things and there should only be a few things that might need to be changed? I think it has to do with how things are executed though?

 I wish I could explain it better, but the main problem is I just don't know enough about it, which of course is why I can't get it working on my own, lol. What it comes down to though is that project I linked above, if I can figure out what needs to be adjusted so that the messages are able to be queued and processed in Unity instead of a Windows console application I will finally have my framework completed, so I appreciate any help you can possibly provide!

Thanks,
Dan

**Comment by MostHated** [comment]
This might give a better example of Unity itself's actual threading https://github.com/Feynmen/UnityThreading The issue is I am just not sure what parts of Fibrous I would end up needing to have use that. : /

**Comment by chrisa23** [comment]
So from reading one of your posts on another library, I think you could create a Unity3DFiber like this:

`    public class Unity3DFiber:FiberBase
    {
        public Unity3DFiber(IExecutor executor):base(executor)
        {
        }

        protected override void InternalEnqueue(Action action)
        {
            UnityMainThreadDispatcher.Instance().Enqueue(() => Executor.Execute(action));
        }
    }`

I didn't test it out, but that is the general idea.  You could get also just do:  UnityMainThreadDispatcher.Instance().Enqueue(action);
But this bypasses the executor abstraction where you can insert error handling, logging and other things into the execution path if needed.

The thing to keep in mind with Fibrous is that it is oriented towards message passing between fibers, using channels (or the event bus).  The Unity3D fiber would just be where you connect handlers back to the Unity thread.  You would not use it to get concurrency itself (i.e run background work on the Unity fiber).  You would normally never use Enqueue on that fiber, but subscribe that fiber to channels and receive events and then do the UI update work associated from those events.

You might have some pool fibers that are intended to do certain work off the main thread and you send them messages through channels to say "do work" or "an event just happened" and then they respond through other channels or through asynchronous request reply.  They can also do work on their own through things like scheduling and then send a message to the Unity fiber.  

Fibrous is very good for some situations, but its ultimately a variation of actor based concurrency.   Not having worked in the realm of Unity3D, its hard for me to say how well Fibrous would work in that domain compared to other libraries.

Hope that helps.  Let me know if you have questions or run into issues.

Thanks,
Chris

**Comment by MostHated** [comment]
Thanks for the reply, I definitely appreciate it. I was able to get it sort of working, but it was again mostly a test / hack job. I believe that the way I am doing it currently is probably going to affect the overall ability for the system to communicate internally, which of course I want to avoid. What  I am using makes full use of channels, subscriptions, publishing, etc, which can be seen here.

https://github.com/sy545633799/NetworkCore/tree/master/photonServer/ExitGamesLibs/Concurrency

I tried to do something similar to what you posted above by putting the Main Thread Dispatcher in the Executor to have it run the Execute, but I don't think it ever made it that far.

So what I tried was within PoolFiber.cs I took Enqueue and did this which worked, but I think I need to remove it from there so it can move through further down the line instead of just sending it to the main thread straight away.

    public void Enqueue(Action action)
    {
      UnityMainThreadDispatcher.Instance().Enqueue(action);
//      lock (this.@lock)
//      {
//        this.queue.Add(action);
//        if (this.started == 0 || this.started == 3)
//          return;
//        if (!this.flushPending)
//        {
//          this.pool.Queue(new WaitCallback(this.Flush));
//          this.flushPending = true;
//        }
//      }
//      this.CounterEnqueue.Increment();
//      this.CounterItemsInQueue.Increment();
    }

The above allowed this.requestFiber.Enqueue(Register); to use the proper request fiber and send it through but its supposed to I guess add it to this.queue.add which is a List, then it triggers the Flush, which it looks like then is supposed to go to : 

    private void Flush(object state)
    {
      List<Action> toExecute = this.ClearActions();
      if (toExecute == null)
        return;
      try
      {
        this.executor.Execute(toExecute);
      }
      finally
      {
        lock (this.@lock)
        {
          if (this.queue.Count > 0)
            this.pool.Queue(new WaitCallback(this.Flush));
          else
            this.flushPending = false;
        }
      }

      this.CounterDequeue.IncrementBy((long) toExecute.Count);
      this.CounterItemsInExecution.IncrementBy((long) -toExecute.Count);
    }

Which then  "this.executor.Execute(toExecute);" goes to the IExecutor interface, which leads to the DefaultExecutor.cs (but also FailSafeBatchExecutor?) Which has this in it which I tried to modify : 

    public void Execute(Action toExecute)
    {
      if (_running)
      {
        toExecute();
      }
    }

    public void Execute(List<Action> toExecute)
    {
      foreach (Action action in toExecute)
      {
        Execute(action);
      }
    }

Which I guess I thought I should put UnityMainThreadDispatcher.Instance().Enqueue(); in only one of those, but according to yours above that should not exactly be the case? I am not exactly following how this whole Execute thing is supposed to work either. It just sort of seems like they loop over each other. I can't seem to figure out how or what actually happens when something hits the aside from it looping back around into itself?

**Comment by chrisa23** [comment]
You don't need to create any other Fibrous components than the simple UnityFiber I showed you.   You definitely don't need to alter the Pool fiber.  The IExecutor is just an abstraction that can be used to wrap execution in try/catch, or add debugging.  Its not intended for concurrency and you don't need to create one.  

You should almost never be using Enqueue.  While that is a public method, it is mostly for Fibrous to pass work based on handlers/subscriptions.

You should be thinking of each fiber as a bubble that communicates through channels and messages.  The unity fiber is a bubble attached to the unity thread.  It should subscribe to channels that tell it it needs to do something on the unity thread.  

Try not using Enqueue at all and that should help you understand things better.  You should try to only communicate through channels or the event bus (which gives one static channel per generic type).

If you can give me an example of what types of things you are trying to use concurrency for, I may be able to give you an example to help you understand better.

**Comment by MostHated** [comment]
I appreciate that info. Here are some examples in which enqueue is actually used outside of files like ObjectPool, ThreadPool, etc.  https://hastebin.com/ukatujurad.scala  Some of them are just snippits of a larger file, some are the whole file, so sorry if its a bit long. It will hopefully help give the bigger picture of what is happening. I put the file name it each "comment header". 

Thank you very very much for assisting with this. I know it's a bit of a pain when I try to explain what is going on and I am not even fully sure. I don't have much, but if I can get things situated properly with this I could try to PayPal you something for helping out if you would like? It is really hard to try to find anyone who knows how to help with these things I am trying to work with who is actually willing to help instead of just ignoring my questions, lol.

Thanks again!

**Comment by MostHated** [comment]
Quick update, all was working well within unity when working on windows, but when I built for Linux and ran it on there finally I got a nullreference to (can't remember exact name) executorfallback, or failoverexecutor? I know it's something close to that lol, I am on my phone though so don't have my error logs. I am excited to see most of the system was working well outside of the concurrency at least. It failed at the point in which it was receiving and about to process an incoming message I believe. I will test somethings out in the morning.

**Comment by chrisa23** [comment]
I had a chance to look a little bit at your code.

You're definitely not using channels much, and doing a lot of fiber enqueue, which is confusing and not the right way to look at Fibrous.

I'm not sure what the base class is in some of the code to know if thats a Unity component (ie  outgoingsociallistenerpeer.cs for example), so I'm not sure how those fit in to the general concurrency.

Here's a brief example of how I usually structure things.  I don't expose the fiber publicly and I only use Enqueue to do something like Initialize code that needs to be in the concurrency bubble.  Inside the bubble is thread safe and can maintain state and use non-concurrent collections, etc...  You basically build little concurrent bubbles that subscribe to events and generate events.  They are decoupled and only talk through events/messages.   

public class Unity3DFiber:FiberBase
    {
        public Unity3DFiber(IExecutor executor):base(executor)
        {
            
        }

        protected override void InternalEnqueue(Action action)
        {
            UnityMainThreadDispatcher.Instance().Enqueue(() => Executor.Execute(action));
        }
    }


    public class World
    {

        private readonly IFIber _fiber = new Unity3DFiber();
        public World()
        {
            EventBus<PhysicsUpdate>.Subscribe(_fiber, OnPhysicsUpdate);
            EventBus<Event2>.Subscribe(_fiber, OnEvent2);
            _fiber.Start();
        }

        private void OnPhysicsUpdate(PhysicsUpdate @event) { }
    }

    public class Physics : IDisposable
    {
        private readonly IFIber _fiber = ThreadFiber.StartNew();

        public Physics()
        {
            EventBus<PhysicsEvent>.Subscribe(_fiber, OnEvent);
            _fiber.Schedule(Update, TimeSpan.FromMilliseconds(16), TimeSpan.FromMilliseconds(16));

            _fiber.Enqueue(Initialize);//Init on our physics fiber so we aren't init-ing on the thread that created us

        }

        private void OnEvent(PhysicsEvent @event) { }



        private void Update()
        {
            // Do your physics stuff
            // Send a message on the EventBus or on a Channel to notify the UnityFiber of stuff
            EventBus<PhysicsUpdate>.Publish(new PhysicsUpdate());
        }

        public void Dispose() { _fiber.Dispose(); }
    }


I hope that helps some.  When you follow patterns like this you can build some fairly complex, highly concurrent systems.   I mostly build trading applications with Fibrous, so I'm in a fairly different domain than video games, although it should be able to work well in that domain.  The key to getting the most out of it is to understand how to structure things.  I really should create some better real world examples.

Let me know if that helps at all and if you have any other questions.

Chris
